

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/ecommerce?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: root

logging:
  level:
    org.springframework.r2dbc.core: debug