

spring:
  main:
    allow-bean-definition-overriding: true
  r2dbc:
    url: r2dbc:mysql://${MYSQL_HOST_PORT}/ecommerce?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: test1234
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties.mail.smtp:
      nickname: 'testLee'
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
logging:
  level:
    org.springframework.r2dbc.core: debug



jwtSecretKey: ${JWT_SECRET}
